// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userinfo

import (
	"context"

	"github.com/987700984/gotest/video/api/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest       = user.IdRequest
	UserInfoReponse = user.UserInfoReponse

	UserInfo interface {
		GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoReponse, error)
		GetUser1(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoReponse, error)
	}

	defaultUserInfo struct {
		cli zrpc.Client
	}
)

func NewUserInfo(cli zrpc.Client) UserInfo {
	return &defaultUserInfo{
		cli: cli,
	}
}

func (m *defaultUserInfo) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoReponse, error) {
	client := user.NewUserInfoClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserInfo) GetUser1(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoReponse, error) {
	client := user.NewUserInfoClient(m.cli.Conn())
	return client.GetUser1(ctx, in, opts...)
}
