// Code generated by goctl. DO NOT EDIT.
package types

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginReponse struct {
	Name string `json:"name"`
}
