// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-test/video/api/rpc/internal/logic/userinfo"
	"go-zero-test/video/api/rpc/internal/svc"
	"go-zero-test/video/api/rpc/types/user"
)

type UserInfoServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserInfoServer
}

func NewUserInfoServer(svcCtx *svc.ServiceContext) *UserInfoServer {
	return &UserInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *UserInfoServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserInfoReponse, error) {
	l := userinfologic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserInfoServer) GetUser1(ctx context.Context, in *user.IdRequest) (*user.UserInfoReponse, error) {
	l := userinfologic.NewGetUser1Logic(ctx, s.svcCtx)
	return l.GetUser1(in)
}
