// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-test/video/api/rpc/internal/logic/useraction"
	"go-zero-test/video/api/rpc/internal/svc"
	"go-zero-test/video/api/rpc/types/user"
)

type UserActionServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserActionServer
}

func NewUserActionServer(svcCtx *svc.ServiceContext) *UserActionServer {
	return &UserActionServer{
		svcCtx: svcCtx,
	}
}

func (s *UserActionServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserInfoReponse, error) {
	l := useractionlogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserActionServer) GetAAF(ctx context.Context, in *user.IdRequest) (*user.UserInfoReponse, error) {
	l := useractionlogic.NewGetAAFLogic(ctx, s.svcCtx)
	return l.GetAAF(in)
}

func (s *UserActionServer) GetUser1(ctx context.Context, in *user.IdRequest) (*user.UserInfoReponse, error) {
	l := useractionlogic.NewGetUser1Logic(ctx, s.svcCtx)
	return l.GetUser1(in)
}
