// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/987700984/gotest/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/users",
				Handler: usersv1Handler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v2/users",
				Handler: usersv2Handler(serverCtx),
			},
		},
		rest.WithPrefix("/v2"),
	)
}
